### ISSUE TITLE
Roadmap to the initial public release

### ISSUE THREAD

**Issue by monatis** [qdrant/quaterion#20]
Updating this one as per @generall's comments.

- [x] Implement evaluation methods and metrics such as MRR etc. WIP #61
- [ ] Create a step-by-step getting-started tutorial for documentation. Needs extra work, but we already have some basic examples.
- [x] Standardize docstrings in a well known format, and generate API docs as a part of CI/CD.
- [ ] Start a changelog, and keep it up-to-date. This one needs attention.
- [ ] Proofread the documentation, and fix minor issues.
- [ ] Finalize #10, and merge it.
- [ ] Tagline issue, #53.

Please add other issues that you consider. I'm also pinning this issue to prioritize it.
